#!/usr/bin/env python3
import sys
import os
import argparse
from PIL import Image, ImageDraw, ImageFont, ImageFilter, ImageOps
import random

VERSION = "0.2.0"

def create_banner(name, output_path="banner.png", bg_path=None):
    width, height = 1280, 400
    
    # 1. Create Background
    if bg_path and os.path.exists(bg_path):
        try:
            bg_img = Image.open(bg_path).convert('RGB')
            # Center crop and resize to 1280x400
            img = ImageOps.fit(bg_img, (width, height), centering=(0.5, 0.5))
            # Add a dark overlay so text is readable
            overlay = Image.new('RGBA', (width, height), (0, 0, 0, 160)) # Darken by ~60%
            img.paste(overlay, (0, 0), overlay)
            print(f"📸 Using custom background: {bg_path}")
        except Exception as e:
            print(f"⚠️ Error loading background, falling back to default: {e}")
            img = Image.new('RGB', (width, height), color=(13, 17, 23))
    else:
        img = Image.new('RGB', (width, height), color=(13, 17, 23)) # GitHub dark theme color
    
    draw = ImageDraw.Draw(img)
    
    # 2. Add subtle "Scanline" pattern (always added for the glitch vibe)
    for y in range(0, height, 4):
        draw.line([(0, y), (width, y)], fill=(20, 24, 30, 50) if bg_path else (20, 24, 30), width=1)
        
    # 3. Add Glow/Background Gradient
    overlay = Image.new('RGBA', (width, height), (0,0,0,0))
    ov_draw = ImageDraw.Draw(overlay)
    ov_draw.ellipse([width//2-400, height//2-300, width//2+400, height//2+300], fill=(0, 232, 232, 20)) # Cyan
    ov_draw.ellipse([width//4-200, height//4-200, width//4+200, height//4+200], fill=(232, 0, 232, 15)) # Magenta
    img.paste(overlay, (0,0), overlay)

    # 4. Text Handling
    font_paths = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"
    ]
    font = None
    for p in font_paths:
        if os.path.exists(p):
            font = ImageFont.truetype(p, 100 if len(name) < 15 else 80)
            break
    if not font:
        font = ImageFont.load_default()

    bbox = font.getbbox(name)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    tx, ty = (width - tw) // 2, (height - th) // 2
    
    # 5. Apply "Glitch" Effect
    draw.text((tx-3, ty), name, font=font, fill=(232, 0, 232)) # Magenta
    draw.text((tx+3, ty), name, font=font, fill=(0, 232, 232)) # Cyan
    draw.text((tx, ty), name, font=font, fill=(255, 255, 255)) # White
    
    # 6. Final "Branding" line
    small_font = None
    for p in font_paths:
        if os.path.exists(p):
            small_font = ImageFont.truetype(p, 16)
            break
    if small_font:
        sub_text = "LOCALOPS AI // UTILITY ENGINE"
        s_bbox = small_font.getbbox(sub_text)
        s_tw = s_bbox[2] - s_bbox[0]
        draw.text(((width - s_tw)//2, ty + th + 40), sub_text, font=small_font, fill=(139, 148, 158))

    # Save
    img.save(output_path)
    return output_path

def main():
    parser = argparse.ArgumentParser(description=f"BrandPulse v{VERSION} - GitHub README Banner Generator")
    parser.add_argument("name", help="The project name to display on the banner")
    parser.add_argument("-o", "--output", default="banner.png", help="Output filename (default: banner.png)")
    parser.add_argument("-b", "--bg", help="Optional path to a custom background image (generated by DALL-E, Gemini, etc.)")
    
    args = parser.parse_args()
    
    print(f"🎨 BrandPulse v{VERSION} // Generating banner for: {args.name}...")
    path = create_banner(args.name, args.output, args.bg)
    print(f"✅ Success! Banner saved to: {path}")

if __name__ == "__main__":
    main()
